[mgr]
ratio = [1,3,4]
show_hidden = true

[open]
prepend_rules = [
  { mime = "image/*", use = "ristretto", orphan = true, for = "linux" },
]

# Define the "ristretto" opener
[opener]
ristretto = [
  { run = 'ristretto "$@"', desc = "Open with Ristretto Image Viewer", orphan = true, for = "linux" }
]

